# Generated by Django 5.2.1 on 2025-06-03 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_product_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
